// client/src/pages/Wallet.tsx

import AuthKeystore from "../components/wallet/AuthKeystore";
import WalletApp from "../components/wallet/WalletApp";

function Wallet() {
  const isLoggedIn: boolean = true;
  return(
    <div className="flex justify-center items-center pb-2 dark:bg-black dark:text-white transition">
      <div className="border text-sm p-4">
        {isLoggedIn ? <WalletApp /> : <AuthKeystore />}
      </div>
    </div>
  );
}

export default Wallet;

// app/pages/wallet.vue
<template>
    <div class="border text-sm p-4 dark:bg-black dark:text-white transition">
        <password v-if="!wallet.isAuth" />
        <new-wallet v-else /> 
    </div>
</template>

<script setup lang="ts">
import { useWalletStore } from '~/stores/wallet';
const wallet = useWalletStore();
</script>
